<a href="https://colab.research.google.com/github/NigeeHettige/Pytorch_Practicals/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **Reshape**

In [7]:
#Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
#Reshape if we don't know the number of items using -1
my_torch = my_torch.reshape(2,-1)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## **View**

In [15]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch2 = my_torch2.view(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch2[0][1] = 2389
my_torch2

tensor([[   0, 2389,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [18]:
#Slices
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Grab a specific item
my_torch3[7]

tensor(7)

In [21]:
#Grab slices
my_torch4 = my_torch3.reshape(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [22]:
my_torch4[:,1]

tensor([1, 3, 5, 7, 9])

In [23]:
#Return column
my_torch4[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])