<a href="https://colab.research.google.com/github/NigeeHettige/Pytorch_Practicals/blob/main/Tensor_math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

## **Addition**

In [4]:
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

## **Addition Longhand**

In [5]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

## **Substraction**

In [6]:
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

## **Multiplication**

In [8]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

## **Division**

In [11]:
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [12]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

## **Modulus**

In [14]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [16]:
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

## **Exponents**

In [17]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [19]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

## **Reassignment**

In [22]:
tensor_a = tensor_a.add(tensor_b)
tensor_a

tensor([11, 14, 17, 20])