<a href="https://colab.research.google.com/github/NigeeHettige/Pytorch_Practicals/blob/main/Tensors_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**


*   A torch ,Tensor is a multi-dimensional matrix containing elements of single data type.

*   Similar to Numpy Arrays,but full of fun things that make them work better on GPU's(vs regular CPU's).

*   default data type of float32.

*   More suitable for deep learning than numpy array.





In [4]:
import torch
import numpy as np


# **Lists**

In [6]:
my_list = [1,2,3,4,5],[6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

## **Numpy Arrays**

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.7839022 , 0.4959069 , 0.71727938, 0.60451244],
       [0.01508338, 0.49028639, 0.52776299, 0.67165684],
       [0.50359285, 0.23226658, 0.673063  , 0.40635238]])

In [8]:
np1.dtype

dtype('float64')

## **Tensors**

In [14]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)
tensor_2d.dtype

tensor([[ 1.2319, -0.0396,  0.2975, -0.0681],
        [ 0.4982,  1.0092, -1.2933,  1.6981],
        [ 1.3519,  0.0612,  1.8264, -0.5175]])


torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out of numpy array
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.7839, 0.4959, 0.7173, 0.6045],
        [0.0151, 0.4903, 0.5278, 0.6717],
        [0.5036, 0.2323, 0.6731, 0.4064]], dtype=torch.float64)